[package]
name = "toylang"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.21", features = ["derive"] }
eyre = "0.6.12"
log = "0.4.22"
common = { path = "common" }
colored = "2.1.0"
